# Generated by Django 4.1.1 on 2022-10-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestparticipant",
            name="phone",
            field=models.CharField(default="000-000-0000", max_length=100),
        ),
    ]
