# Generated by Django 4.1.1 on 2022-10-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest_app", "0002_contestparticipant_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestparticipant",
            name="is_leader",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contestteam",
            name="course",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
